### ISSUE TITLE
Data Processing in MUSIC

### ISSUE THREAD

**Issue by Vandana92GS** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#14]
Hi,
In the MUSIC code provided there is no data file available. Therefore I would like to know what is the data cube size of the data  in terms of samples , chirps and receivers. Is there any preprocessing performed on the data before applying it to the music algorithm?

Thank you,
Vandana

**Comment by Xiangyu-Gao** [comment]
The number of receivers is 8 and I assumed the configuration of samples or chirps does not affect the MUSIC code since it is only for the doa estimation.

Is there any preprocessing performed on the data before applying it to the music algorithm? - Well, good question. If you have a static object/target, you can always average the covariance matrixes to reduce the noise which gives you better performance for doa estimation.

**Comment by Vandana92GS** [comment]
Thank you for the reply. So can I assume  the input  data matrix to represent the no.of receivers, samples and frame number?

**Comment by Xiangyu-Gao** [comment]
I did not remember the details of the input data, but max. dimension should be 2. You can try no.of receivers by samples, or samples by no.of receivers, or no.of receivers by frames, or frames by no.of receivers.
