### ISSUE TITLE
Reading .bin

### ISSUE THREAD

**Issue by xdindincx** [Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification#20]
Hi Xiangyu, 

I have a raw adc data file (.bin) I have obtained from Infineon's BGT60TR24C. I have renamed it and placed it in the location as mentioned in read_bin.m. However I am getting an error 

```
Error using reshape
Size arguments must be real integers.

Error in readDCA1000 (line 59)
    LVDS = reshape(LVDS, numADCSamples*numRX, numChirps);

Error in read_bin (line 10)
data = readDCA1000(folder_location, samples);
```

Here is the file: 

[bin_data.zip](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/files/13184165/bin_data.zip)

Can you please help with this. 

Thanks.

**Comment by Xiangyu-Gao** [comment]
Your radar configuration might be different from mine, e.g.,  numADCSamples, numRX, numChirps, etc.

**Comment by mahajanpushkar** [comment]
Hi Xiangyu,

I am using IWR6843ISK-ODS and recorded a .bin file from mmWave Industrial Visualizer. On using the function readDCA1000 I get the same error. I am using the correct parameters from my config file and ran code before line generating error of readDCA1000.m (using function as provided in TI docs and you have the same function) and got following outputs:
1.  adcData = 117104x1 double
2. filesize = 117104
3. LVDS = 1x58552 complex double
4. numADCBits = 16
5. numADCSamples = 384
6. numChirps = 38.119791666666664
7. numLanes = 2
8. numRX = 4

Now the problem is numChirps is not an integer and if I round it off then it can't reshape as (size of LVDS) > (size of numADCSamples*numRX*numChirps).

From config file, 'profileCfg 0 60 216 7 200 0 0 20 1 384 2000 0 0 158' where 384 is the numADC samples.

Here's the bin file.
[pHistBytes_1.zip](https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification/files/13662395/pHistBytes_1.zip).
 
Could you please suggest what can be wrong?
Thank you.

**Comment by Xiangyu-Gao** [comment]
`readDCA1000.m` is designed for _DCA1000_ hardware. I did not verify the `readDCA1000` for the ADC bin data collected from the _mmWave Industrial Visualizer_ and the bin data format might be different.   Besides, 'profileCfg 0 60 216 7 200 0 0 20 1 384 2000 0 0 158' should give a hint of the number of chirps. Is it close to your calculated one 38.119791666666664?
